/**
 * MIT License
 *
 * Copyright (c) 2026 rainy-juzixiao
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import chalk from 'chalk';
import {scanGitHistory, openGit} from '#@/git';
import {computeNextVersion, buildVersionCommitMessage} from '#@/version';
import {createPullRequest} from '#@/github';
import {defaultConfig} from '#@/config/index.js';
import {resolveConfig} from '#@/utils/resolve-config.js';

export interface AutoOptions {
    configPath?: string;
    owner?: string;
    repo?: string;
    token?: string;
    base?: string;
    path?: string;
    dryRun?: boolean;
}

export async function autoAction(options: AutoOptions): Promise<void> {
    let cfg = await resolveConfig(options.configPath);

    if (cfg != null) {
        console.log(`Successfully loaded config: ${options.configPath}`);
    } else {
        console.log(chalk.yellow('Warning: use default config'));
        cfg = defaultConfig;
    }

    try {
        const result = await scanGitHistory({repoPath: options.path});
        const next = computeNextVersion(result.latestTag, result.commits);

        if (next === null || next === undefined) {
            console.log(chalk.yellow('No version bump warranted. Nothing to release.'));
            return;
        }

        const from = result.latestTag ?? 'initial';
        console.log(chalk.bold(`${from} → ${chalk.green(next.newVersion)} (${next.bump})`));

        if (options.dryRun === true) {
            console.log(chalk.dim('(dry-run — stopping before commit & PR)\n'));
            return;
        }

        const git = openGit(options.path);
        const msg = buildVersionCommitMessage(next.newVersion, next.bump);

        const token = options.token !== undefined && options.token !== null && options.token !== ''
            ? options.token
            : (process.env.GH_TOKEN ?? process.env.GITHUB_TOKEN);
        if (token !== undefined && token !== null && token !== '') {
            const remotes = await git.getRemotes(true);
            const origin = remotes.find(r => r.name === 'origin');
            if (origin !== undefined && origin !== null) {
                const pushUrl = origin.refs.push !== undefined && origin.refs.push !== null && origin.refs.push !== ''
                    ? origin.refs.push
                    : origin.refs.fetch;
                const authedUrl = pushUrl.replace('https://', `https://x-access-token:${token}@`);
                if (authedUrl !== pushUrl) {
                    await git.remote(['set-url', 'origin', authedUrl]);
                }
            }
        }

        await git.add('.');
        await git.commit(msg);
        await git.addTag(`v${next.newVersion}`);

        await git.push('origin', result.currentBranch);
        await git.pushTags('origin');

        const commitList = next.commits
            .map(c => {
                const scope = c.scope !== undefined && c.scope !== null && c.scope !== ''
                    ? `(${c.scope})`
                    : '';
                return `- ${c.type}${scope}: ${c.description}`;
            })
            .join('\n');

        // TODO: PR — Use pullRequestConfig for body (auto)
        //       Same as `pr` and `release-pr` commands: replace hardcoded body
        //       with header + commitList + footer from config, plus draft,
        //       labels, releaseLabel, skipLabel and date.

        const header = cfg.pullRequest.header === null ? "The Release Pull Request Is Created\n-----------------\n" : cfg.pullRequest.header;

        const body = [
            header,
            `## ${next.newVersion}\n`,
            commitList,
            '',
            '---',
            'This Request Generated by release-my-work',
        ].join('\n');

        const pr = await createPullRequest({
            token,
            owner: options.owner as string,
            repo: options.repo as string,
            head: result.currentBranch,
            base: (options.base ?? 'main') as string,
            title: msg.split('\n')[0],
            body,
        });

        console.log(chalk.green(`Pull Request created: ${chalk.underline(pr.url)}`));
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        console.error(chalk.red('Error:'), errorMessage);
        process.exit(1);
    }
}
