/**
 * MIT License
 *
 * Copyright (c) 2026 rainy-juzixiao
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import chalk from 'chalk';
import {scanGitHistory, openGit} from '#@/git';
import {computeNextVersion} from '#@/version';
import {createPullRequest} from '#@/github';
import {defaultConfig} from '#@/config/index.js';
import {resolveConfig} from '#@/utils/resolve-config.js';

export interface PrOptions {
    owner?: string;
    repo?: string;
    configPath?: string;
    token?: string;
    base?: string;
    path?: string;
}

export async function prAction(options: PrOptions): Promise<void> {
    try {
        let cfg = await resolveConfig(options.configPath);

        if (cfg != null) {
            console.log(`Successfully loaded config: ${options.configPath}`);
        } else {
            console.log(chalk.yellow('Warning: use default config'));
            cfg = defaultConfig;
        }

        const git = openGit(options.path);
        const currentBranch = (await git.branch()).current;

        const result = await scanGitHistory({repoPath: options.path});
        const next = computeNextVersion(result.latestTag, result.commits);

        const title = next
            ? `chore(release): ${next.newVersion}`
            : 'chore(release): manual release';
        // TODO: PR — Use pullRequestConfig for title templating
        //       Replace hardcoded title with pullRequestConfig.titlePattern:
        //         titlePattern = "chore${scope}: release${component} ${version}"
        //         → "chore(release): 1.2.3"
        //       Template vars: ${scope}, ${component}, ${version}

        const commitList = (next !== undefined && next !== null ? next.commits : result.commits)
            .map(c => {
                const scope = c.scope !== undefined && c.scope !== null && c.scope !== ''
                    ? `(${c.scope})`
                    : '';
                return `- ${c.type}${scope}: ${c.description}`;
            })
            .join('\n');

        // TODO: PR — Use pullRequestConfig.header/body/footer for body
        //       Currently the body is hardcoded.  Planned:
        //         body = pullRequestConfig.header
        //              + commitList
        //              + pullRequestConfig.footer
        //       header/footer support template interpolation (${version}, etc.).
        //       Also add config-driven date line (pullRequestConfig.date)
        //       and apply pullRequestConfig.releaseLabel transitions.
        const body = [
            `## ${next?.newVersion ?? 'Release'}\n`,
            commitList,
            '',
            '---',
            'This Request Generated by release-my-work',
        ].join('\n');

        // TODO: PR — Use pullRequestConfig.draft flag
        //       createPullRequest accepts a draft parameter;
        //       pass pullRequestConfig.draft instead of always
        //       creating a normal PR.

        // TODO: PR — Apply labels from pullRequestConfig.labels
        //       After creation, add labels via the GitHub API
        //       Issues.addLabels.

        // TODO: PR — Handle pullRequestConfig.skipLabel
        //       If the latest commit (or branch) contains the
        //       skipLabel, skip PR creation.

        const pr = await createPullRequest({
            token: options.token,
            owner: options.owner as string,
            repo: options.repo as string,
            head: currentBranch,
            base: (options.base ?? 'main') as string,
            title,
            body,
        });

        console.log(chalk.green(`Pull Request created: ${chalk.underline(pr.url)}`));
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        console.error(chalk.red('Error:'), errorMessage);
        process.exit(1);
    }
}
