/**
 * MIT License
 *
 * Copyright (c) 2026 rainy-juzixiao
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import chalk from 'chalk';
import {scanGitHistory, openGit} from '#@/git';
import {computeNextVersion} from '#@/version';
import {createPullRequest, addLabelsToPR} from '#@/github';
import {defaultConfig} from '#@/config/index.js';
import {resolveConfig} from '#@/utils/resolve-config.js';

function interpolateTemplate(template: string, vars: Record<string, string>): string {
    return template.replace(/\$\{(\w+)\}/g, (_, key: string) => vars[key] ?? '');
}

export interface PrOptions {
    owner?: string;
    repo?: string;
    configPath?: string;
    token?: string;
    base?: string;
    path?: string;
}

export async function prAction(options: PrOptions): Promise<void> {
    try {
        let cfg = await resolveConfig(options.configPath);

        if (cfg != null) {
            console.log(`Successfully loaded config: ${options.configPath}`);
        } else {
            console.log(chalk.yellow('Warning: use default config'));
            cfg = defaultConfig;
        }

        const git = openGit(options.path);
        const currentBranch = (await git.branch()).current;

        const result = await scanGitHistory({repoPath: options.path});
        const next = computeNextVersion(result.latestTag, result.commits);

        // Use pullRequestConfig.titlePattern via template interpolation
        const title = next
            ? interpolateTemplate(cfg.pullRequest.titlePattern, {
                scope: '(release)',
                component: cfg.packageName,
                version: next.newVersion,
            })
            : interpolateTemplate(cfg.pullRequest.titlePattern, {
                scope: '(release)',
                component: cfg.packageName,
                version: 'manual',
            });

        const commitList = (next !== undefined && next !== null ? next.commits : result.commits)
            .map(c => {
                const scope = c.scope !== undefined && c.scope !== null && c.scope !== ''
                    ? `(${c.scope})`
                    : '';
                return `- ${c.type}${scope}: ${c.description}`;
            })
            .join('\n');

        // Use pullRequestConfig.header/footer for body composition
        const header = cfg.pullRequest.header !== ''
            ? cfg.pullRequest.header
            : `## ${next?.newVersion ?? 'Release'}\n`;

        const dateLine = cfg.pullRequest.date
            ? `\n${new Date().toISOString().split('T')[0]}\n`
            : '';

        const footer = cfg.pullRequest.footer !== ''
            ? `\n\n${cfg.pullRequest.footer}`
            : '';

        const body = [
            header,
            dateLine,
            '',
            commitList,
            footer,
            '',
            '---',
            'This PR was generated by release-my-work.',
        ].join('\n');

        // Use pullRequestConfig.draft flag
        const pr = await createPullRequest({
            token: options.token,
            owner: options.owner as string,
            repo: options.repo as string,
            head: currentBranch,
            base: (options.base ?? 'main') as string,
            title,
            body,
            draft: cfg.pullRequest.draft,
        });

        console.log(chalk.green(`Pull Request created: ${chalk.underline(pr.url)}`));

        // Apply labels from pullRequestConfig.labels
        if (cfg.pullRequest.labels.length > 0) {
            await addLabelsToPR(
                options.owner as string,
                options.repo as string,
                pr.number,
                cfg.pullRequest.labels,
                options.token,
            );
            console.log(chalk.dim(`Labels added: ${cfg.pullRequest.labels.join(', ')}`));
        }

        // Apply releaseLabel transitions
        for (const [key, value] of Object.entries(cfg.pullRequest.releaseLabel)) {
            const targetLabel = `${key}: ${value}`;
            try {
                await addLabelsToPR(
                    options.owner as string,
                    options.repo as string,
                    pr.number,
                    [targetLabel],
                    options.token,
                );
            } catch { /* ok */
            }
        }
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        console.error(chalk.red('Error:'), errorMessage);
        process.exit(1);
    }
}
